// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izjtqhzjqxwydnfmdjth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6anRxaHpqcXh3eWRuZm1kanRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjcwNjUsImV4cCI6MjA2OTkwMzA2NX0.E2gIDdT5jRHTzSxdK9MC6RFk6qYuxskwvnpDP4DdurQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});